#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  brew help
  ;;
"list")
  brew tap
  ;;
"list-version")
  $0 list # no version for brew tap
  ;;
"which")
  exit 0 # no which for brew tap
  ;;
"install")
  brew tap $*
  ;;
"remove")
  brew untap $*
  ;;
"upgrade")
  exit 0 # no upgrade for brew tap
  ;;
"upgrade-all")
  exit 0 # no upgrade for brew tap
  ;;
"package-manager")
  echo "brew tap"
  ;;
"package-manager-version")
  upkg os "package-manager-version"
  ;;
"which-self")
  which brew
  ;;
"install-self")
  upkg os "install-self"
  ;;
esac

## todo only mac
