#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  brew help
  ;;
"list")
  brew list --cask
  ;;
"list-version")
  brew list --cask --versions | cut -d "," -f 1 | tr -s " " "@"
  ;;
"which")
  brew --prefix "$1"
  ;;
"install")
  brew install --cask $*
  ;;
"remove")
  brew uninstall --cask $*
  ;;
"upgrade")
  brew upgrade --cask $*
  ;;
"upgrade-all")
  brew upgrade --cask
  ;;
"package-manager")
  echo "brew --cask"
  ;;
"package-manager-version")
  upkg os "package-manager-version"
  ;;
"which-self")
  which brew
  ;;
"install-self")
  upkg os "install-self"
  ;;
esac
