#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  cargo
  ;;
"list")
  ls "$CARGO_BIN"
  ;;
"list-version")
  cut -f 1-2 --delimiter="|" <(cargo install-update --list | tail --lines=+4 | head --lines=-2 | sed -E 's/ +/|/g') | tr -d v | tr "|" "@"
  ;;
"which")
  echo "$CARGO_BIN"/$1
  ;;
"install")
  cargo install $*
  ;;
"remove")
  cargo uninstall $*
  ;;
"upgrade")
  cargo install-update $*
  ;;
"upgrade-all")
  cargo install-update -a
  ;;
"install-self")
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  ;;
esac
