#!/usr/bin/env bash

subcommand="$1"
shift

function transform_version() {
  input="$1"
  if echo "$input" | grep -q "@"; then
    name=$(echo "$input" | cut -d'@' -f1)
    version=$(echo "$input" | cut -d'@' -f2)
    echo "--version $version $name"
  else
    echo "$input"
  fi
}

case "$subcommand" in
"test-existence")
  cargo
  ;;
"list")
  ls "$CARGO_BIN"
  ;;
"list-version")
  cut -f 1-2 --delimiter="|" <(cargo install-update --list | tail --lines=+4 | head --lines=-2 | sed -E 's/ +/|/g') | tr -d v | tr "|" "@"
  ;;
"which")
  echo "$CARGO_BIN"/"$1"
  ;;
"install")
  cargo install "$(transform_version "$1")"
  ;;
"remove")
  cargo uninstall "$(transform_version "$1")"
  ;;
"upgrade")
  cargo install-update $1
  ;;
"upgrade-all")
  cargo install-update -a
  ;;
"package-manager")
  echo "cargo"
  ;;
"package-manager-version")
  cargo --version | cut -d " " -f 2
  ;;
"which-self")
  which cargo
  ;;
"install-self")
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  ;;
esac
