#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  command -v github-releases >/dev/null || exit 1
  ;;
"list-no-version")
  github-releases list-no-version "$@"
  ;;
"list-version") 
  github-releases list-version "$@"
  ;;
"list")
  github-releases list "$@"
  ;;
"listable-name")
  github-releases listable-name "$@"
  ;;
"install")
  github-releases install "$@"
  ;;
"remove")
  github-releases remove "$@"
  ;;
"upgrade")
  github-releases upgrade "$@"
  ;;
"upgrade-all")
  github-releases upgrade-all "$@"
  ;;
"which")
  github-releases which "$@"
  ;;
"package-manager")
  github-releases package-manager
  ;;
"package-manager-version")
  github-releases package-manager-version
  ;;
"which-self")
  which github-releases
  ;;
"install-self")
  upkg gp install gitea.localhost/user1/gitlike-packages
  ;;
"help")
  github-releases help
  ;;
*)
  echo "gh: unknown subcommand: $subcommand" >&2
  exit 1
  ;;
esac
