#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  command -v github-releases >/dev/null || exit 1
  ;;
"list-no-version")
  github-releases list-no-version "$@"
  ;;
"list-version") 
  github-releases list-version "$@"
  ;;
"list")
  github-releases list "$@"
  ;;
"listable-name")
  github-releases listable-name "$@"
  ;;
"install")
  github-releases install "$@"
  ;;
"remove")
  github-releases remove "$@"
  ;;
"upgrade")
  github-releases upgrade "$@"
  ;;
"upgrade-all")
  github-releases upgrade-all "$@"
  ;;
"which")
  github-releases which "$@"
  ;;
"package-manager")
  github-releases package-manager
  ;;
"package-manager-version")
  github-releases package-manager-version
  ;;
"which-self")
  which github-releases
  ;;
"install-self")
  upkg gp install gitea.localhost/user1/gitlike-packages
  ;;
"help")
  github-releases help
  ;;
"extra-env")
  target="${1:?Target expected}"
  cat <<EOF
export PACKAGE_MANAGER_DATA_HOME="\${XDG_DATA_HOME}/git-releases/git-packages"
export PACKAGES_HOME="\${PACKAGE_MANAGER_DATA_HOME}/packages"
export PACKAGE_NAME='$($0 listable-name "$target")'
export PACKAGE_PATH="\${PACKAGES_HOME}/\${PACKAGE_IDENTIFIER}"
EOF
  ;;
"extra-hook-types")
  extra-hook-types "$1" git-packages
  ;;
"extra-info")
  echo '# The structure of the package at install time is (provided for convenience only):'
  echo -e "\n$(tree -L 3 --noreport "$($0 which "$1")" | sed 's/^/# /')\n\n"
  ;;
"get-hook-code-for-extra-hook-type")
  get-hook-code-for-extra-hook-type "$1" github-releases "$2"
  ;;
*)
  echo "gh: unknown subcommand: $subcommand" >&2
  exit 1
  ;;
esac
