#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  command -v git-packages >/dev/null || exit 1
  ;;
"list-no-version")
  git-packages list-no-version
  ;;
"list-version") 
  git-packages list-version
  ;;
"list")
  git-packages list
  ;;
"listable-name")
  git-packages listable-name "$1"
  ;;
"install")
  git-packages install "$1"
  ;;
"remove")
  git-packages remove "$1"
  ;;
"upgrade")
  git-packages upgrade "$1"
  ;;
"upgrade-all")
  git-packages upgrade-all
  ;;
"which")
  git-packages which "$1"
  ;;
"package-manager")
  git-packages package-manager
  ;;
"package-manager-version")
  git-packages package-manager-version
  ;;
"which-self")
  which git-packages
  ;;
"install-self")
  upkg gp install gitea.localhost/user1/gitlike-packages
  ;;
"help")
  git-packages help
  ;;
"extra-env")
  target="${1:?Target expected}"
  cat <<EOF
export PACKAGE_MANAGER_DATA_HOME="\${XDG_DATA_HOME}/gitlike-packages/git-packages"
export PACKAGES_HOME="\${PACKAGE_MANAGER_DATA_HOME}/packages"
export PACKAGE_NAME='$($0 listable-name "$target")'
export PACKAGE_PATH="\${PACKAGES_HOME}/\${PACKAGE_IDENTIFIER}"
EOF
  ;;
"extra-hook-types")
  extra-hook-types "$1" git-packages
  ;;
"extra-info")
  echo '# The structure of the package at install time is (provided for convenience only):'
  echo -e "\n$(tree -L 3 --noreport "$($0 which "$1")" | sed 's/^/# /')\n\n"
  ;;
"get-hook-code-for-extra-hook-type")
  get-hook-code-for-extra-hook-type "$1" git-packages "$2"
  ;;
*)
  echo "gh: unknown subcommand: $subcommand" >&2
  exit 1
  ;;
esac
