#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  go help || exit 1
  ;;
"list")
  ls "$GOPATH"/bin
  ;;
"list-version")
  ls "$GOPATH"/bin # no version for go, so just list
  ;;
"which")
  echo "$GOPATH"/bin/"$1"
  ;;
"install")
  go install "$1"
  ;;
"remove")
  rm "$GOPATH"/bin/"$1"
  ;;
"upgrade")
  go get -u "$1"
  ;;
"upgrade-all")
  cd "$GOPATH"/bin && go get -u -- *
  ;;
"package-manager")
  echo "go"
  ;;
"package-manager-version")
  go version | cut -d " " -f 3 | tr -d "go"
  ;;
"which-self")
  which go
  ;;
"install-self")
  brew install go
  ;;

esac
