#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  npm help || exit 1
  ;;
"list")
  npm list -g --depth=0 --json | jq -r '.dependencies | keys[] as $k | "\($k)"'
  ;;
"list-version")
  npm list -g --depth=0 --json | jq -r '.dependencies | keys[] as $k | "\($k)@\(.[$k].version)"'
  ;;
"with-version")
  $0 list-version | grep "$1"
  ;;
"install")
  npm install -g $*
  ;;
"remove")
  npm uninstall -g $*
  ;;
"upgrade")
  npm update -g $*
  ;;
"upgrade-all")
  npx npm-check --global --update-all
  ;;
"install-self")
  brew install node
  ;;
esac
