#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"test-existence")
  brew help || exit 1
  ;;
"list")
  brew list --formula $*
  ;;
"list-version")
  brew list --formula --versions | cut -d "," -f 1 | tr -s " " "@"
  ;;
"which")
  brew --prefix "$1"
  ;;
"install")
  brew install $*
  ;;
"remove")
  brew uninstall $*
  ;;
"upgrade")
  brew upgrade $*
  ;;
"upgrade-all")
  brew upgrade
  ;;
"package-manager")
  echo "brew"
  ;;
"package-manager-version")
  brew --version | head -n 1 | cut -d " " -f 2
  ;;
"which-self")
  which brew
  ;;
"install-self")
  /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  ;;
esac
