#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"list")
  pip3 list --format freeze | cut -d "=" -f 1
  ;;
"list-version")
  pip3 list --format freeze | tr -s "==" "@"
  ;;
"which")
  pip3 show "$1" | grep Location | cut -d " " -f 2
  ;;
"install")
  pip3 install "${1//@/==}"
  ;;
"remove")
  pip3 uninstall "${1//@/==}"
  ;;
"upgrade")
  pipupgrade "$1"
  ;;
"upgrade-all")
  pipupgrade
  ;;
"test-existence")
  pip3
  ;;
"package-manager")
  echo "pip3"
  ;;
"package-manager-version")
  pip3 --version | cut -d " " -f 2
  ;;
"which-self")
  which pip3
  ;;
"install-self")
  brew install python
  ;;
"help") ;;
esac
