#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"list")
  pip3 list --format freeze | cut -d "=" -f 1
  ;;
"list-version")
  pip3 list --format freeze | tr -s "==" "@"
  ;;
"which")
  pip3 show "$1" | grep Location | cut -d " " -f 2
  ;;
"install")
  pip3 install $*
  ;;
"remove")
  pip3 uninstall $*
  ;;
"upgrade")
  pipupgrade $*
  ;;
"upgrade-all")
  pipupgrade
  ;;
"test-existence")
  pip3
  ;;
"install-self")
  piu i python
  ;;
esac
