#!/usr/bin/env bash

subcommand="$1"
shift

case "$subcommand" in
"list")
  # For default packages, only list the package name, for packages installed with a version, list the package name and version
  for package in "$XDG_DATA_HOME"/upkg/test/packages/*; do
    package_name="$(basename "$package" | cut -d "@" -f 1)"
    version="$(basename "$package" | cut -d "@" -f 2)"
    default="$(basename "$package" | cut -d "@" -f 3)"
    if [[ "$default" == "default" ]]; then
      echo "$package_name"
    else
      echo "$package_name@$version"
    fi
  done
  ;;
"list-version")
  for package in "$XDG_DATA_HOME"/upkg/test/packages/*; do
    basename "$package"
  done
  ;;
"which")
  package="$(cut -d "@" -f 1 <<<"$1")"
  version="$(cut -d "@" -f 2 <<<"$1")"
  if [[ -z "$version" ]]; then
    ls "$XDG_DATA_HOME"/upkg/test/packages/"$1"@*@default
  else
    ls "$XDG_DATA_HOME"/upkg/test/packages/"$1"
  fi
  ;;
"install")
  package="$(cut -d "@" -f 1 <<<"$1")"
  version="$(cut -d "@" -f 2 <<<"$1")"
  if [[ -z "$version" ]]; then
    version="0.0.1@default"
  fi
  touch "$XDG_DATA_HOME/upkg/test/packages/$package@$version"
  ;;
"remove")
  package="$(cut -d "@" -f 1 <<<"$1")"
  version="$(cut -d "@" -f 2 <<<"$1")"
  if [[ -z "$version" ]]; then
    rm "$XDG_DATA_HOME"/upkg/test/packages/"$1"@*@default
  else
    rm "$XDG_DATA_HOME"/upkg/test/packages/"$1"
  fi
  ;;
"upgrade") # upgrading only works on default packages
  # take the version from the package file, then increment the patch version by 1
  version="$(basename "$XDG_DATA_HOME"/upkg/test/packages/"$1"*"@default" | cut -d "@" -f 2)"
  patch_version="$(echo "$version" | cut -d "." -f 3)"
  new_patch_version="$((patch_version + 1))"
  new_version="$(echo "$version" | sed "s/$patch_version$/$new_patch_version/")"
  touch "$XDG_DATA_HOME/upkg/test/packages/$1@$new_version@default"
  rm "$XDG_DATA_HOME"/upkg/test/packages/"$1@$version@default"
  ;;
"upgrade-all")
  # iterate through all default packages and increment the patch version by 1
  for package in "$XDG_DATA_HOME"/upkg/test/packages/*@default; do
    upkg test upgrade "$(basename "$package" | cut -d'@' -f1)"
  done
  ;;
"test-existence")
  [[ -d "$XDG_DATA_HOME"/upkg/test/packages ]] || exit 1
  ;;
"package-manager")
  echo "test"
  ;;
"package-manager-version")
  echo "1.0.0"
  ;;
"which-self")
  echo "$XDG_DATA_HOME"/upkg/test/packages
  ;;
"install-self")
  mkdir -p "$XDG_DATA_HOME"/upkg/test/packages
  ;;
"help") ;;
esac
