#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "$(realpath "${BASH_SOURCE[0]}")")" &>/dev/null && pwd)

package_manager="$1"

if [ -z "$package_manager" ]; then
  package_manager="help" # default to help
fi

# short commands are _<letter> to avoid conflicts with subcommands, since the package reasons about the first arg to determine if it is a subcommand or a package name

package_managers=("os" "pip" "cargo" "npm" "git-packages" "brew-cask" "brew-tap" "stew" "go" "test")

case "$package_manager" in
"gp" | "gitp" | "gitpackages" | "gpackages")
  package_manager="git-packages"
  ;;
"_b" | "brew")
  package_manager="os"
  ;;
"_p" | "pip3" | "python")
  package_manager="pip"
  ;;
"bcask" | "b-cask")
  package_manager="brew-cask"
  ;;
"btap" | "b-tap")
  package_manager="brew-tap"
  ;;
"_c" | "rust")
  package_manager="cargo"
  ;;
"_n" | "node")
  package_manager="npm"
  ;;
"_s" | "git-release")
  package_manager="stew"
  ;;
"_t" | "tst" | "tester")
  package_manager="test"
  ;;
"lpm" | "list-package-managers")
  echo "${package_managers[@]}" | tr ' ' '\n'
  exit 0
  ;;
"h" | "help")
  cat "$SCRIPT_DIR"/help_message
  ;;
esac

package_manager_command_path="$SCRIPT_DIR"/package-managers/__"$package_manager"

if [ ! -f "$package_manager_command_path" ]; then

  for package_manager in "${package_managers[@]}"; do
    $0 "$package_manager" "$@"
  done
  exit 0
else
  shift
fi

function zet_diff_output() {
  local output1 output2
  output1="$($0 "$package_manager" ${1:?})"
  output2="$($0 "$package_manager" ${2:?})"
  zet diff <(echo "$output1") <(echo "$output2")
}

pkg_command() { $package_manager_command_path "$@"; }

backup_file="$MDEPENDENCIES"/"$package_manager"

if [ ! -f "$backup_file" ]; then
  touch "$backup_file"
fi

subcommand="$1"
shift

pkg_command test-existence >/dev/null 2>&1 || pkg_command install-self

case "$subcommand" in
es | "echo-self")
  echo "$package_manager"
  ;;
l | "list")
  pkg_command list
  ;;
lv | "list-version")
  pkg_command list-version "$@"
  ;;
lnv | "list-no-version")
  pkg_command list_version "$@" | cut -d'@' -f1 | sort | uniq
  ;;
lvpm | "list-version-package-manager")
  list_version="$($0 "$package_manager" list-version)"
  sed -e "s/^/$package_manager:/" <<<"$list_version"
  ;;
lwpm | "list-with-package-manager")
  list="$($0 "$package_manager" list)"
  sed -e "s/^/$package_manager:/" <<<"$list"
  ;;
wv | "with-version")
  pkg_command list-version | grep "$1"
  ;;
wvpm | "with-version-package-manager")
  $0 "$package_manager" list-version-package-manager | grep "$1"
  ;;
wwpm | "with-package-manager")
  $0 "$package_manager" list-with-package-manager | grep "$1"
  ;;
v | "version")
  $0 "$package_manager" with-version "$@" | cut -d'@' -f2
  ;;
ct | "count")
  pkg_command list | wc -l
  ;;
ii | "is-installed")
  pkg_command list | grep "^$1$"
  ;;
iipm | "is-installed-package-manager")
  pkg_command list | grep -q "^$1$" && echo "$package_manager"
  ;;
b | "backup")
  $0 "$package_manager" added >>"$backup_file"
  ;;
rb | "read-backup")
  cat "$backup_file" 2>/dev/null
  ;;
db | "delete-backup")
  rm "$backup_file"
  ;;
rpb | "replace-backup")
  $0 "$package_manager" delete-backup
  $0 "$package_manager" backup
  ;;
rfb | "remove-from-backup")
  $0 "$package_manager" read-backup | grep -v "^$1$" >"$backup_file"
  ;;
bf | "backup-file")
  echo "$backup_file"
  ;;
m | "missing")
  zet_diff_output read-backup list
  ;;
a | "added")
  zet_diff_output list read-backup
  ;;
d | "difference")
  zet single <($0 "$package_manager" read-backup) <($0 "$package_manager" list)
  ;;
miv | "missing-installable-verbose")
  missing_list="$($0 "$package_manager" missing)" && exit 0
  echo "missing packages for $(tput setaf 3)$package_manager$(tput sgr0):"
  echo "$missing_list" | sed 's/^/  /'
  echo ""
  exit 1
  ;;
im | "install-missing")
  missing_list="$($0 "$package_manager" missing | tr "\n" " ")"
  [ -z "$missing_list" ] || pkg_command install "$missing_list"
  ;;
nm | "none-missing")
  ! $0 "$package_manager" missing-installable | grep -E "\w" >/dev/null
  ;;
mpm | "missing-package-managers")
  $0 "$package_manager" none-missing || echo "$package_manager"
  ;;
i | "install")
  pkg_command install "$@"
  ;;
r | "remove")
  pkg_command remove "$@"
  $0 "$package_manager" remove-from-backup "$1"
  ;;
is | "install-self")
  pkg_command install-self "$@"
  ;;
u | "upgrade")
  pkg_command upgrade "$@"
  ;;
w | "which")
  pkg_command which "$@"
  ;;
"link")
  pkg_command link "$@"
  ;;
ua | "upgrade-all")
  pkg_command upgrade-all "$@"
  ;;
pm | "package-manager")
  pkg_command package-manager
  ;;
pmv | "package-manager-version")
  pkg_command package-manager-version
  ;;
wpm | "which-package-manager")
  pkg_command which-self
  ;;
h | "help")
  pkg_command help
  ;;
esac
