#!/usr/bin/env bash

target="${1?Target expected}"
type="${2:-git-packages}"
package_path="$(package-path "$target" "$type")"
package_name="$(basename "$package_path")"
host_package_identifier="$(host-package-ident "$target" "$type")"
echo "Building package $host_package_identifier for $type..."
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$type"
install_script_path="$DATA_HOME/install/$host_package_identifier"
upgrade_build_strategy_path="$DATA_HOME/upgrade-build-strategy/$host_package_identifier"

if [[ -f "$install_script_path" ]]; then
    echo "Install script found."
  else
    echo "Generating install script..."
    [[ -f "$package_path/$package_name" ]] && package_executable="$package_path/$package_name"
    [[ -f "$package_path/build.zig" ]] && build_zig="$package_path/build.zig"

    # Check for files and store them in arrays
    package_executable=""
    build_zig=""
    declare -a makefiles
    declare -a install_scripts

    [[ -f "$package_path/$package_name" ]] && package_executable="$package_path/$package_name"
    [[ -f "$package_path/build.zig" ]] && build_zig="$package_path/build.zig"
    for file in GNUmakefile makefile Makefile; do
      [[ -f "$package_path/$file" ]] && makefiles+=("$file")
    done
    for file in "$package_path"/install*; do
      [[ -f "$file" ]] && install_scripts+=("$file")
    done

    # Generate hint text dynamically
    link_hint=$([[ -n "$package_executable" ]] && echo "(executable with same name as package found)")
    zig_hint=$([[ -n "$build_zig" ]] && echo "(build.zig found)" || echo "(no build.zig found!)")
    make_hint=$([[ ${#makefiles[@]} -gt 0 ]] && echo "(makefiles found: ${makefiles[*]})")
    install_script_hint=$([[ ${#install_scripts[@]} -gt 0 ]] && echo "(install scripts found: ${install_scripts[*]})")

    while true; do
      # Ask user for install strategy
      echo "Select install strategy:"
      options=(
        "1) none"
        "2) link $link_hint"
        "3) build with zig $zig_hint"
        "4) run install script $install_script_hint"
        "5) make $make_hint"
        "6) run a custom script"
      )
      strategy_choice=$(printf '%s\n' "${options[@]}" | fzf --prompt="Enter choice: ")
      if [[ -z "$strategy_choice" ]]; then
        ask "No choice made. Do you want to cancel & exit?" Y && exit 1
      else
        ask "You chose $strategy_choice, is that correct?" Y && break 2
      fi
    done

    # Check if the user made a choice
    if [[ -z "$strategy_choice" ]]; then
      echo "No choice made. Exiting..."
      exit 1
    fi

    # Extract the strategy index from the choice
    strategy_index=$(printf '%s\n' "${options[@]}" | grep -nxF "$strategy_choice" | cut -d: -f1)

    install_code="#!/usr/bin/env bash\n\n"
    skip_edit=false

    case "$strategy_index" in
      "1") # none
        echo "Don't install anything. Empty script generated. Done, exiting..."
        skip_edit=true
        ;;
      "2") # link
        if [[ -n "$package_executable" ]]; then
          if ask "Executable with same name as package found. Do you want add linking it to the install script?" Y; then
            read -rp "Rename to (optional, leave empty to not rename): " rename_to
            target="$HOMEBIN/${rename_to:-$package_name}"
            install_code+="ln -sf \"$package_executable\" \"$target\"\n"
            install_code+="chmod +x \"$target\"\n"
          fi
        fi
        if [[ -z "$package_executable" ]] || ask "Do you want to link something else?" N; then
          # Loop to select executables
          while true; do
            echo "Select a file to link:"
            linkme=$( ( { cd "$package_path" || exit; } | tree -L 3 -if --noreport | cut -d / -f '2-' | tail -n '+2' | fzf --prompt="Select a file to link: ") )
            read -rp "Rename to (optional, leave empty to not rename): " rename_to
            target="$HOMEBIN/${rename_to:-$linkme}"
            install_code+="ln -sf \"$package_path/$linkme\" \"$target\"\n"
            install_code+="chmod +x \"$target\"\n"
            ask "Do you want to link something else?" N || break
          done
        fi
        ;;
      "3") # zig
        read -rp "Additional build args (optional, leave empty to not use any): " build_args
        install_code+="zig build install --prefix \"$HOME/.local\" $build_args\n"
        ;;
      "4") # install-script
        # Loop to select install scripts
        if [[ "${#install_scripts[@]}" -gt 0 ]]; then
          if ask "Install scripts found. Do you want to add them to the main install script?" Y; then
            for script in "${install_scripts[@]}"; do
              read -rp "Additional args for $script (optional): " args
              install_code+="chmod +x \"$script\"\n"
              install_code+="$script $args\n"
            done
          fi
        fi
        if [[ "${#install_scripts[@]}" -eq 0 ]] || ask "Do you want to add a/another script to the main install script?" N; then
          # Loop to select install scripts
          while true; do
            echo "Select a script to run:"
            script=$( ( { cd "$package_path" || exit; } | tree -L 3 -if --noreport | cut -d / -f '2-' | tail -n '+2' | fzf --prompt="Select a script to run: " ) )
            read -rp "Additional args (optional): " args
            install_code+="chmod +x \"$package_path/$script\"\n"
            install_code+="$package_path/$script $args\n"
            ask "Do you want to run something else?" N || break
          done
        fi
        ;;
      "5") # make
        # if there is only one makefile, use it
        makefile=""
        if [[ ${#makefiles[@]} -eq 1 ]]; then
          makefile="${makefiles[0]}"
        else
          # select makefile
          echo "Select a makefile to use:"
          select selectedmakefile in "${makefiles[@]}"; do
            makefile="$selectedmakefile"
            break
          done
        fi
        install_code+="make -C \"$package_path\" -f \"$makefile\" install\n"
        ;;
      "6") # run
        # No additional code needed
        ;;
    esac

    # Save generated install script
    mkdir -p "$(dirname "$install_script_path")"
    echo -e "$install_code" > "$install_script_path"
   
    if [[ "$skip_edit" = true ]]; then
      exit 0
    fi

    # Ask user to edit the install script
    ask "Install script generated. Do you want to edit the script?" N && $VISUAL "$install_script_path"

  fi

  # Ask user what strategy we should choose when upgrading: always, ask-yes, ask-no, never

  if ! [[ -f "$upgrade_build_strategy_path" ]] && ask "Do you want to set an upgrade strategy?" Y; then
    while true; do
      echo "Select upgrade strategy:"
      options=(
        "1) always"
        "2) ask-yes"
        "3) ask-no"
        "4) never"
      )
      strategy_choice=$(printf '%s\n' "${options[@]}" | fzf --prompt="Enter choice: " | cut -d ' ' -f '2-')
      if [[ -z "$strategy_choice" ]]; then
        ask "No choice made. Do you want to cancel & exit?" Y && exit 1
      else
        ask "You chose $strategy_choice, is that correct?" Y && break 2
      fi
    done

    mkdir -p "$(dirname "$upgrade_build_strategy_path")"
    echo "$strategy_choice" > "$upgrade_build_strategy_path"
  fi
  chmod +x "$install_script_path"
  # Run the install script
  "$install_script_path"