#!/usr/bin/env bash

# parameters

target="${1:?Target expected}"
type="${2:?package manager expected}"
hook_type="${3:-default}"

# derived variables


package_path="$(upkg "$type" which "$target")"

if [[ -z "$package_path" ]]; then
  echo "Was not able to find path for $target of $type. Probably not installed. Please ensure the name is correct, the package is installed, and then try again." >&2
  exit 1
fi

identifier="$(upkg "$type" listable-name "$target")"

if [[ -z "$identifier" ]]; then
  echo "Was not able to find identifier for $target of $type. However, we were able to find its path: $package_path. More likely than not this is due to an unexpected change in the configuration or directory structure, or a bug. Please report this issue." >&2
  exit 1
fi

PACKAGE_HOOK_HOME="$PACKAGE_MANAGER_WRAPPER_DATA_HOME/hooks/$identifier"
hook_path="$PACKAGE_HOOK_HOME/$hook_type"

echo "Building package $identifier for $type..."

mkdir -p "$PACKAGE_MANAGER_WRAPPER_DATA_HOME" "$PACKAGE_MANAGER_WRAPPER_CACHE_HOME" "$PACKAGE_MANAGER_WRAPPER_TMP_HOME"

declare -a basic_options extra_options options

while true; do
  # Ask user for hook type
  basic_options=(
    "1) none"
    "2) run a custom script"
  )
  mapfile -t extra_options < <(upkg "$type" extra-hook-types "$target")
  options=("${basic_options[@]}" "${extra_options[@]}")
  
  action_choice=$(printf '%s\n' "${options[@]}" | fzf --prompt="Select hook type: ")
  if [[ -z "$action_choice" ]]; then
    ask "No choice made. Do you want to cancel & exit?" Y && exit 1
  else
    ask "You chose $action_choice, is that correct?" Y && break
  fi
done

# Check if the user made a choice
if [[ -z "$action_choice" ]]; then
  echo "No choice made. Exiting..."
  exit 1
fi

# Extract the action index from the choice
action_index=$(printf '%s\n' "${options[@]}" | grep -nxF "$action_choice" | cut -d: -f1)

hook_code="$(
  cat <<EOF
#!/usr/bin/env bash

# This is an auto-generated hook created by upkg (package manager: $type) for $identifier, found at $package_path. Created at $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# This file will not be regenerated unless manually recreated/deleted. Feel free to edit this file.

# upkg environment variables:

export XDG_DATA_HOME="\${XDG_DATA_HOME:-\$HOME/.local/share}"
export UPKG_DATA_HOME="\$XDG_DATA_HOME/upkg"
export XDG_CACHE_HOME="\${XDG_CACHE_HOME:-\$HOME/.cache}"
export UPKG_CACHE_HOME="\$XDG_CACHE_HOME/upkg"
export XDG_TMP_HOME="\${TMPDIR:-\$HOME/.tmp}"
export UPKG_TMP_HOME="\$XDG_TMP_HOME/upkg"
export PACKAGE_MANAGER_WRAPPER_DATA_HOME="\$UPKG_DATA_HOME/$type"
export PACKAGE_MANAGER_WRAPPER_CACHE_HOME="\$UPKG_CACHE_HOME/$type"
export PACKAGE_MANAGER_WRAPPER_TMP_HOME="\$UPKG_TMP_HOME/$type"
export XDG_BIN_HOME="\${XDG_BIN_HOME:-\$HOME/.local/bin}"
export PACKAGE_IDENTIFIER='$identifier'
export PACKAGE_HOOK_HOME="\${PACKAGE_MANAGER_WRAPPER_DATA_HOME}/hooks/\${PACKAGE_IDENTIFIER}"
export package_path_at_install='$package_path'

# package manager environment variables:

$(upkg "$type" extra-env "$target")

# extra info as provided by the package manager, if any:
EOF
)"

hook_code+="\n\n"
hook_code+="$(upkg "$type" extra-info "$target")"
hook_code+="\n\n"

skip_edit=false

case "$action_index" in
  "1") # none
    echo "Don't install anything. Empty script generated."
    skip_edit=true
    ;;
  "2") # run
    # No additional code needed
    ;;
  *) # extra hook type
    mkfifo "$PACKAGE_MANAGER_WRAPPER_TMP_HOME/extra-hook-out"
    upkg "$type" get-hook-code-for-extra-hook-type "$target" "$action_index" 3> "$PACKAGE_MANAGER_WRAPPER_TMP_HOME/extra-hook-out" &
    hook_code+="$(cat "$PACKAGE_MANAGER_WRAPPER_TMP_HOME/extra-hook-out")"
    rm "$PACKAGE_MANAGER_WRAPPER_TMP_HOME/extra-hook-out"
    ;;
esac

# Save generated hook
mkdir -p "$(dirname "$hook_path")"
echo -e "$hook_code" > "$hook_path"

if [[ "$skip_edit" != true ]]; then
  # Ask user to edit the hook
  ask "Hook generated. Do you want to edit the script?" N && $VISUAL "$hook_path"
fi

chmod +x "$hook_path"

if ask "Hook created. Do you want to run it now?" Y; then
  "$hook_path"
fi