#!/usr/bin/env bash

target="${1?Target expected}"
type="${2:?package manager expected}"
hook_type="${3:-default}"
identifier="$(upkg "$type" listable-name "$target")"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$type"
HOOK_HOME="$DATA_HOME/hooks/$identifier"
hook_path="$HOOK_HOME/$hook_type"

create-hook "$target" "$type" "$hook_type" && "$hook_path"
