#!/usr/bin/env bash

target="${1:?Target expected}"
type="${2:?package manager expected}"
hook_type="${3:-default}"
identifier="$(upkg "$type" listable-name "$target")"
PACKAGE_HOOK_HOME="$PACKAGE_MANAGER_DATA_HOME/hooks/$identifier"
hook_path="$PACKAGE_HOOK_HOME/$hook_type"

create-hook "$target" "$type" "$hook_type" && "$hook_path"
