#!/usr/bin/env bash

command="${1:-git-packages}"
type="${2:?no type given}"
host_package_identifier="$(host-package-ident "${3:?missing target arg}" "$command")"

tgtpath="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$command/$type/$host_package_identifier"

if [[ -f "$tgtpath" ]]; then
  $VISUAL "$tgtpath"
else
  echo "No $type item found for $host_package_identifier" >&2
fi