#!/usr/bin/env bash

target="${1:?Target expected}"
type="${2:?package manager expected}"
hook_type="$3"
identifier="$(upkg "$type" listable-name "$target")"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$type"
HOOK_HOME="$DATA_HOME/hooks/$identifier"
mkdir -p "$HOOK_HOME"
if [[ -z "$hook_type" ]]; then
  hook_type=$( ( { cd "$HOOK_HOME" || exit; } && tree -L  -if --noreport | cut -d / -f '2-' | tail -n '+2' | fzf --prompt="Select hook: " ) )
fi

if [[ -z "$hook_type" ]]; then
  echo "No hook selected" >&2
  exit 1
fi

hook_path="$HOOK_HOME/$hook_type"

if [[ -f "$hook_path" ]]; then
  echo "$hook_path"
else
  echo "No $hook_type hook found for $identifier of $type" >&2
fi