#!/usr/bin/env bash

input="${1:?input is required}"
input="${input#https://}"
input="${input#http://}"
input="${input%.git}"
input="${input%/}"
if [[ $input == "${XDG_DATA_HOME:-$HOME/.local/share}/upkg/${2:-git-packages}/"* ]]; then # a full path of the package
  echo "$input" | rev | cut -d '/' -f 1-3 | rev
elif [[ $input == */*/* ]]; then # already a host package identifier
  echo "$input" 
else
  package-path "$input" "$2" | rev | cut -d '/' -f 1-3 | rev
fi