#!/usr/bin/env bash

target="${1:?Target expected}"
type="${2:?package manager expected}"
identifier="$(upkg "$type" listable-name "$target")"
PACKAGE_RUN_ON_HOME="$PACKAGE_MANAGER_WRAPPER_DATA_HOME/run-on/$identifier"
mkdir -p "$PACKAGE_RUN_ON_HOME"

event="${3:-*}"
policy="${4:-*}"
hook_type="${5:*}"

IFS=$'\n'
shopt -s nullglob

for hook in "$PACKAGE_RUN_ON_HOME"/$event/$policy/$hook_type; do
  rm "$hook"
done

unset IFS
shopt -u nullglob