#!/usr/bin/env bash

# parameters

target="${1:?Target expected}"
type="${2:?package manager expected}"
hook_type="${3:-default}"

# derived variables

identifier="$(upkg "$type" listable-name "$target")"
if [[ -z "$identifier" ]]; then
  echo "Was not able to find identifier for $target of $type. Aborting." >&2
  exit 1
fi
PACKAGE_HOOK_HOME="$PACKAGE_MANAGER_WRAPPER_HOOKS_DATA_HOME/$identifier"
PACKAGE_RUN_ON_HOME="$PACKAGE_MANAGER_WRAPPER_RUN_ON_DATA_HOME/$identifier"
hook_path="$PACKAGE_HOOK_HOME/$hook_type"


IFS=$'\n'
shopt -s nullglob

for prev_hook_location in "$PACKAGE_RUN_ON_HOME"/*/*/"$hook_type"; # PACKAGE_RUN_ON_HOME/<run_on>/<policy>/<hook_type>
do
  rm "$prev_hook_location"
done

unset IFS

declare -a run_ons
run_ons=(
  "install"
  "upgrade"
  # more in the future
)

for run_on in "${run_ons[@]}"; do
  while true; do
    options=(
      "1) always"
      "2) ask-yes"
      "3) ask-no"
      "4) never"
    )
    policy_choice=$(printf '%s\n' "${options[@]}" | fzf --prompt="Select policy for running hook $hook_type on $run_on: " | cut -d ' ' -f '2-')
    if [[ -z "$policy_choice" ]]; then
      ask "No choice made. Do you want to cancel & exit?" Y && exit 1
    else
      ask "You chose $policy_choice, is that correct?" Y && break
    fi
  done
  run_on_path="$PACKAGE_RUN_ON_HOME/$run_on/$policy_choice"
  mkdir -p "$run_on_path"
  ln -sf "$hook_path" "$run_on_path/$hook_type"
done

shopt -u nullglob