#!/usr/bin/env bash

target="${1:?Target expected}"
type="${2:?package manager expected}"
hook_type="${3:-default}"
identifier="$(upkg "$type" listable-name "$target")"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$type"
HOOK_HOME="$DATA_HOME/hooks/$identifier"
hook_path="$HOOK_HOME/$hook_type"
RUN_ON_HOME="$DATA_HOME/run-on/$identifier"


IFS=$'\n'
shopt -s nullglob

for prev_hook_location in "$RUN_ON_HOME"/*/*/"$hook_type"; # RUN_ON_HOME/<run_on>/<policy>/<hook_type>
do
  rm "$prev_hook_location"
done

unset IFS

declare -a run_ons
run_ons=(
  "install"
  "upgrade"
  # more in the future
)

for run_on in "${run_ons[@]}"; do
  while true; do
    options=(
      "1) always"
      "2) ask-yes"
      "3) ask-no"
      "4) never"
    )
    policy_choice=$(printf '%s\n' "${options[@]}" | fzf --prompt="Select policy for running hook $hook_type on $run_on: " | cut -d ' ' -f '2-')
    if [[ -z "$policy_choice" ]]; then
      ask "No choice made. Do you want to cancel & exit?" Y && exit 1
    else
      ask "You chose $policy_choice, is that correct?" Y && break
    fi
  done
  run_on_path="$RUN_ON_HOME/$run_on/$policy_choice"
  mkdir -p "$run_on_path"
  ln -sf "$hook_path" "$run_on_path/$hook_type"
done

shopt -u nullglob