#!/usr/bin/env bash

command="${1:-git-packages}"
host_package_identifier="${2:?no host package identifier given}"
upgradepath="${XDG_DATA_HOME:-$HOME/.local/share}/upkg/$command/run-on-upgrade/$host_package_identifier"

if [[ -f "$upgradepath" ]]; then
  upgrade_strategy="$(cat "$upgradepath")"
else
  echo "No upgrade strategy found. Default to 'always'"
  upgrade_strategy="always"
fi

should-run-install-script "$upgrade_strategy"